### ISSUE TITLE
ImportError: No module named 'Cookie'

### ISSUE THREAD

**Issue by jvlomax** [jotes/django-cookies-samesite#2]
* django-cookies-samesite version: 0.1.2
* Django version: 2.0.7
* Python version: 3.5.2
* Operating System: ubuntu 16.04

### Description

Installing django-cookies-samesite and running the local server results in an error
importing the "Cookies" package

### What I Did

```
$> pip install django-cookies-samesite
$> python manage.py runserver
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/vagrant/portal/config/wsgi.py", line 29, in <module>
    application = get_wsgi_application()
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    middleware = import_string(middleware_path)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django_cookies_samesite/middleware.py", line 1, in <module>
    import Cookie
ImportError: No module named 'Cookie'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vagrant/portal/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django_extensions/management/commands/runserver_plus.py", line 258, in handle
    self.inner_run(options)
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django_extensions/management/commands/runserver_plus.py", line 304, in inner_run
    handler = get_internal_wsgi_application()
  File "/home/vagrant/.virtualenvs/portal/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'config.wsgi.application' could not be loaded; Error importing module.

```
I'm guessing either this package is ment for python2.7, or there is a missing requirement in the requirements file?

**Comment by jotes** [comment]
@jvlomax Hi!
For unknown reason I haven't see this issue (haven't received any notification from Github.
I'll fix this today!

**Comment by jotes** [comment]
@jvlomax I noticed that you've created a fork with the patch for this issue -> feel free to create a PR. I'll gladly accept it!

**Comment by jvlomax** [comment]
@jotes No worries. I have created a PR with a fix, though I have not got around to testing it just yet. I'd be happy to test it tomorrow and report back.

**Comment by jotes** [comment]
Hey @jvlomax ,

The 0.2.0 version is out, could you download it and check if it works for you?
It's tested against python 2.7, 3.6 and 3.7 (only locally, because travis-ci supports only 2.7 and 3.6)

**Comment by jvlomax** [comment]
I can confirm that it works
