### ISSUE TITLE
Package is not installing

### ISSUE THREAD

**Issue by Headmaster11** [jotes/django-cookies-samesite#52]
* django-cookies-samesite version: 0.5.1
* Django version: 1.11
* Python version: 3.6
* Operating System: macos

### Description

Trying to install django-cookies-samesite==0.5.1

### What I Did

```
pip install  django-cookies-samesite==0.5.1

  ERROR: Command errored out with exit status 1:
   command: /Users/headmaster/PycharmProjects/leverx/espresa/espresa/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ck/49fxlz752255s6shtmk457h80000gn/T/pip-install-pus8n399/django-cookies-samesite_6f9880e60b6e456a87c9470a19115db9/setup.py'"'"'; __file__='"'"'/private/var/folders/ck/49fxlz752255s6shtmk457h80000gn/T/pip-install-pus8n399/django-cookies-samesite_6f9880e60b6e456a87c9470a19115db9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/ck/49fxlz752255s6shtmk457h80000gn/T/pip-pip-egg-info-w87ydqe3
       cwd: /private/var/folders/ck/49fxlz752255s6shtmk457h80000gn/T/pip-install-pus8n399/django-cookies-samesite_6f9880e60b6e456a87c9470a19115db9/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/ck/49fxlz752255s6shtmk457h80000gn/T/pip-install-pus8n399/django-cookies-samesite_6f9880e60b6e456a87c9470a19115db9/setup.py", line 44, in <module>
      readme = open('README.rst').read()
    File "/Users/headmaster/.pyenv/versions/3.6.15/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2145: ordinal not in range(128)

```

**Comment by yurymarozau** [comment]
May be useful:

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
